# Generated by Django 5.0.6 on 2024-06-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='test@domain.com', max_length=254),
            preserve_default=False,
        ),
    ]
